### PR TITLE
docs: update installation version to be less strict

### PR DESCRIPTION
**Pull request by Ziinc**
This updates readme to be less strict

### CODE REVIEW

**Comment by hauleth** [comment]
That is not correct, as it is against SemVer that we are using there.

**Comment by Ziinc** [comment]
It's so that users who attempt to install will get the highest minor version and latest features. If they need to pin a specific minor version then it is up to them to add the patch number

**Comment by hauleth** [comment]
I think that we should provide the meaningful value in the `README.md`. Just as with stable libraries you see `~> 3.1` not `~> 3` in installation instructions. We (through SemVer) guarantee that `0.2.0` and `0.2.99` will not introduce any breaking changes, but we *do not* guarantee that `0.2.1` and `0.3.0` will behave the same way. We can cause breaking changes between these two which will break user expecations. If you want what you have described there, then we can simply put `>= 0.0.0` there and call it a day. It will be the same "users who attempt to install will get the highest ~~minor~~ version".

**Comment by Ziinc** [comment]
I'm fine with keeping it strict, just makes it a little more tedious to keep the readme up to date.
In any case, `0.x.y` semver is [not guaranteed to be stable](https://semver.org/#spec-item-4), so it is not the same as `>= 0.0.0` as breaking changes are to be expected with a `mix deps.update`.

**Pull request closed without merging**
