### PR TITLE
fix: allow limiting amount of decompressed data

### LINKED ISSUE #4: Gzip test coverage and configuration
- [ ] Port over max chunk tests from logflare
- [ ] Allow max chunk number to be configurable via `Application.get_env/3`
cc @hauleth

### PR DESCRIPTION
**Pull request by hauleth**
Close #4

### CODE REVIEW

**Review by Ziinc — CHANGES_REQUESTED** [review]
could you add in testing + docs on usage? 🙏

**Comment by hauleth** [comment]
Actually it is partly tested (in "chunked decompression" test), but yeah, sure. I will add additional tests.

**Comment by hauleth** [comment]
About docs - do we need anything extra over [`Plug.Conn.read_body/2` information about `:length`](https://hexdocs.pm/plug/1.15.2/Plug.Conn.html#read_body/2)?

**Comment by Ziinc** [comment]
docs needed is namely the fact that `:length` option would be directly passed to read_body.
Should also try to use the default `Plug.Parser` [value](https://hexdocs.pm/phoenix/file_uploads.html#configuring-upload-limits) , not sure if we have a way to determine the value of the option provided at runtime. Could probably hardcode it to `8_000_000`, but might result in some discrepancies in behaviour in that case.

capping it to upload limit is good idea, much more precise than chunk counts. 👍

**Comment by hauleth** [comment]
Everything added, along with zipbomb-ish example for Gzip decoder.

**Review by Ziinc — APPROVED** [review]
looks great ❤️

**Comment by Ziinc** [comment]
~~Needs to be rebased on latest ci fixes for it to get merged~~

**Pull request merged**
